### ISSUE TITLE
autoc wrong return type

### ISSUE THREAD

**Issue by RoXioTD** [gadicc/node-yahoo-finance2#110]
Hi,
first of all i want to say thank you for this project.

I think the `autoc` function currently has the wrong return type.
Currently its returning a `Promise` of type `AutocResult` (`Promise<AutocResult>`), however it should return a `Promise` of type ` AutocResultSet` (`Promise<AutocResultSet>`).
Either the function has a wrong return type or the docs needs to be updated, because the docs [Auto complete usage](https://github.com/gadicc/node-yahoo-finance2/blob/devel/docs/modules/autoc.md#usage) are showing that the function should return a `Promise` of type ` AutocResultSet`.

**Comment by gadicc** [comment]
That's exactly right, @RoXioTD .  Thanks for reporting this and figuring out the specifics.  We even perform some runtime validation that we're returning an `AutocResultSet` (and not `AutocResult`), wonder how this slipped through.  Anyways, all fixed now :grin:
