### ISSUE TITLE
`quoteCombine` for `quoteSummary` function ?

### ISSUE THREAD

**Issue by RoXioTD** [gadicc/node-yahoo-finance2#114]
Currently its possible to combine multiple `quote` calls into a single call via `quoteCombine`, see also [QuoteCombine docs](https://github.com/gadicc/node-yahoo-finance2/blob/devel/docs/other/quoteCombine.md).
I was wondering if it would make sense to offer the exact same functionality for the `quoteSummary` function?

**Comment by PythonCreator27** [comment]
I don't think so, since the yahoo finance API's endpoint doesn't support multiple symbols at once. The whole point of combining network calls would be lost. What do you think, @gadicc?

**Comment by gadicc** [comment]
Hey @RoXioTD, thanks for the issue.  @PythonCreator27 is correct, `quote` is I think the only Yahoo API that allows multiple symbols in a single network request.  However, I do plan to provide some guidance on how to do best do a number of concurrent requests (even though each one will involve it's own network request).

To get started (this will become part of the docs soon):

```js
const symbols = ['TSLA', 'MSFT', 'AAPL'];

// Will perform one request at a time, one after the other
const data = [];
for (let symbol of symbols)
  data.push(await yahooFinance.quoteSummary(symbol));

// Will perform all requests simultaneously (not great for > ~8 symbols)
const data = Promise.all(symbols.map(symbol => yahooFinance.quoteSummary(symbol)));
```

Both approaches return an identical result, the only different is that the 2nd method performs all requests at the same time.

You can use something like [p-limit](https://www.npmjs.com/package/p-limit) to limit the number of simultaneous requests to something like 8 or whatever is appropriate for your network.  I'm currently working on baking this in with #76, so you can watch that space.  That will make it easier to limit the total concurrent calls across different functions or callbacks, which has the same convenience of `quoteCombine` - even though it will still be with multiple network requests.   You can do it already without a limit but you might choke your connection if you do it with too many requests simultaneously.

Hope that all makes sense and let me know if you have any more questions.  The code above is not tested but should be good :sweat_smile:

**Comment by RoXioTD** [comment]
@PythonCreator27 @gadicc  Thx for your answers and explanantions. Sounds good to me.
