### ISSUE TITLE
GitHub Issue (and PR) Templates, Labels, GH Discussions

### ISSUE THREAD

**Issue by PythonCreator27** [gadicc/node-yahoo-finance2#116]
# GitHub Issue (and PR) Templates, Labels, GH Discussions
Having a structured issue template is sort of becoming a requirement as new issues are coming in. Take #114 for example. You can't immediately tell what kind of issue it is. While the library gives a URL for creating new issues when validation errors occur, it isn't exactly a structured template. Also having PR templates will help organize the PRs (new module, validation fix, etc.).

## Templates
- Bug report
- Feature request
- Question (not answered by the docs)
- Major change (RFC?)
- Meta issue, like #8 or this one
- Validation
- Docs related

## Adding templates
Issue templates are added in the `.github/ISSUE_TEMPLATE` directory. Adding a `config.yml` to that directory and preventing people from making blank issues is another task. PR templates are added under the `.github/PULL_REQUEST_TEMPLATE` directory.

## Adding labels
Labels will need to be added first.
- `bug`
- `feature request`
- `question`
- `rfc` (maybe this fits under meta)
- `meta`
- `validation`
- `docs`

PR Labels:
- `validation fix`
- `other fix`
- `new module`
- `other enhancement`
- `docs`
- `other`

## GH Discussions
These aren't a must-have, but they can be useful when discussing things. Probably not as useful for this repository, but can be used as a mini stackoverflow.

# Task List
- [x] Issue Templates
- [x] PR Templates
- [x] Issue Labels
- [x] PR Labels
- [x] GH Discussions
- [x] `config.yml`

What are your thoughts, @gadicc? Any labels/templates to add/remove? I can send a PR for all of the templates. The discussions and labels have to be done by a repo owner, though.

**Comment by gadicc** [comment]
Thanks, @PythonCreator27, this is really great!  Would be amazing if you can do the templates, thanks so much for your initiative here.

I turned on Discussions, have never used them before personally, let's see how they work out.

Re labels (note, GitHub uses the same labels for issues and PRs):

* `meta` - added
* `validation` - added
* `new module` - added

The rest already existed as other names (e.g. 'feature request' is covered by `enhancement`).  The PRs we need to re-use the same labels, so, `validation` + `bug` + (closed, or `released`) would cover "validation fix", I think, etc.  Let's start off with what we have now and see how we go.

Thanks so much, this is really helpful especially now as I have some other things going on.
