### ISSUE TITLE
Convert to ESM module (BREAKING).  Target: end of beta cycle.

### ISSUE THREAD

**Issue by gadicc** [gadicc/node-yahoo-finance2#126]
**Rationale**
[Sindre Sorhus: Get Ready For ESM](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77)

**Implementation**
[Sindre Sorhus: Pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)

**Sugested timeline**

* Target: before first non-beta release (planned around July)
* When things get quiet on other stuff, perhaps we can release with an `rc` tag.

**Comment by gadicc** [comment]
Actually we can do the "Dual" approach from the Rationale link above, then it's not a breaking change.  We'll make the library ESM but also have a build step that transpiles a CommonJS fallback.

**Comment by PythonCreator27** [comment]
😆 I was about to open an issue for this! You beat me to it! Yes, I agree. ESModules will a lot better for the rest of the ecosystem.

## Suggested Timeline
- Start planning important/helpful/required breaking changes
- Incorporate this into that list
- Release new major version with the changes when the list's length is long enough

## Dual
I would say that we should not stick to the dual approach. We can start with it, but we should remove the CJS fallback at the end of April.

**Comment by gadicc** [comment]
Thanks, @PythonCreator27, glad to hear others are on board for this :pray: 

Yes, I don't want to support dual moving forward.  But I think we can give people a bit more time to get ready if it doesn't cost us anything.  Maybe 6 months with a big fat warning with anyone loading the CJS fallback.

From what I understood, as long as we provide the fallback, it won't be a breaking change and should be transparent to the user.  It will only be a breaking change / new major version when we drop the fallback.
