### ISSUE TITLE
Latest news

### ISSUE THREAD

**Issue by dimdenGD** [gadicc/node-yahoo-finance2#135]
# Feature Request

## Wanted Feature
When I call `.search` (for example) for `GME`, it returns 3 month old news. How do I make it return latest news if it's possible?

## Potential Example Usage
This feature *could* be used in the following way:
```ts
yfinance.search("GME", { sort: "latest" });
```

**Comment by gadicc** [comment]
Hey @dimdenGD, thanks for your issue.

`search`, specifically, returns the same results you get from the search bar on Yahoo Finance.
Indeed, if I type `GME` into the search bar at the top of https://finance.yahoo.com/, I get 3 month old articles.
We don't have any control over how this sort works.

However, clearly there is later news, e.g. further down on https://finance.yahoo.com/quote/GME?p=GME&.tsrc=fin-srch.
I had a quick look and wrote down some initial findings at #138.
At this point however, I have to admit, this feature probably won't be coming in the short term.
