### ISSUE TITLE
Custom error reporters

### ISSUE THREAD

**Issue by gadicc** [gadicc/node-yahoo-finance2#15]
@pudgereyem on #14:

> ### Custom jest reporters prevent `--verbose` to output individual tests
> I like to run `jest --verbose` so that I can see the results of the individual tests when working. However, the custom reporters that was added, [see code here](https://github.com/gadicc/node-yahoo-finance2/blob/devel/jest.config.js#L11-L13) prevents that behaviour. In order to see the individual tests (as shown in the above section) I had to comment out those. See below.
> 
> ```
> // jest.config.js
> 
> module.exports = {
>   preset: 'ts-jest',
>   setupFilesAfterEnv: [
>     "<rootDir>/tests/setupTests.js"
>   ],
>   testEnvironment: 'node',
>   testPathIgnorePatterns: [
>     "/node_modules/",
>     "/api/"
>   ],
>   // reporters: [
>   //   '<rootDir>/tests/reporter.js',
>   //   '<rootDir>/tests/summary-reporter.js',
>   // ],
> };
> ```
> 
> What are your thoughts on this? I personally appreciate seeing what different tests are running.

**Comment by gadicc** [comment]
Ahh, I thought something had changed with the tests but couldn't put a finger on it :sweat_smile: 

Ok, so the customer error reporter hides console output for passing tests.

This is because e.g. we have a lot of tests that test *failing* validation, and you've seen how much console output that generates.  (So you can imagine how I didn't notice the missing test names after getting rid of thousands other lines :sweat_smile:)

Clearly an unintended consequence is that it's hiding the console output that lists the name of the test itself.

I think the solution is actually to drop the custom reporter and look into a way to disable console output temporarily just for those specific tests.  Will report back.

**Comment by pudgereyem** [comment]
@gadicc, yes I could see what you tried to do there. I agree that it's a good idea to drop the custom reporter for now and then solve that problem you presented without unexpected side effects 👍

**Comment by gadicc** [comment]
Great, it's done! :tada:
