### ISSUE TITLE
quoteCombine not returning error as expected

### ISSUE THREAD

**Issue by ytsruh** [gadicc/node-yahoo-finance2#150]
# Bug Report

## Describe the bug
Running the quoteCombine method within a loop I am able to return data as expected until I reach a symbol that cannot be found.  Instead of returning an Error that can be caught in try/catch. Nothing appears to be returned. Typically my list of symbols is kept upto date but I'm unable to guarantee this is 100% in line with what Yahoo has

## Minimal Reproduction
Calling await getData causes my server to 'hang' and eventually time out

`const getData = async (array) => {
   
      let x = [];
      let y = [];
      for (const row of array) {
        try {
          console.log(row.symbol);
          const result = await yahooFinance.quoteCombine(`${row.symbol}.L`);
          console.log(result);
          x.push({ [row["symbol"]]: result });
        } catch (err) {
          console.log(err);
         y.push(err)
        }
      }
      return { x , y };
    };`

## Environment
Browser or Node: Node 
Node version (if applicable): 14 & 15
Npm version: 7.4
Browser verion (if applicable): N/A
Library version (e.g. `1.10.1`):

**Comment by gadicc** [comment]
Hey @ytsruh, thanks for reporting this.

Looks like Yahoo's API silently skips missing symbols.

I'll add a check at the end of the request to look for any symbols we asked for and didn't get back, and `resolve()` such cases with `undefined`, which is how `quote()` handles these symbols on a single call.

Might only get to this next week but watch this space :D

**Comment by gadicc** [comment]
This is fixed in `devel` but will probably only get released next week.

Also want to look at:

* [ ] What happens if `quoteCombine()` is called again after timeout but before previous request returns.
* [ ] Should add similar `undefined` test for regular `quote()`

@ytsruh thanks again for reporting.

**Comment by ytsruh** [comment]
Honestly.....thank you. I was convinced it was something I was/wasn't doing. 

Will keep an eye on this and test when released to report back. Appreciate the quick response as well! Happy to help if/however I can

**Comment by gadicc** [comment]
Hey @ytsruh, we just released all of last months "devel" changes in 1.11.0.  Let us know how it goes.  I'm still leaving this issue open as there are some linked issues (particularly  #151), which hopefully I can finish up soon now that a number of other higher priorities have been released.

**Comment by ytsruh** [comment]
Sorry, this has taken me a long time to look at. However, pleased to say this seemed to do the trick! 

I didnt have any issues when a symbol is 'not found'. So thanks for the fix!

**Comment by gadicc** [comment]
Hey @ytsruh, no worries at all, and thanks for reporting back!

May you be blessed with ever resolving symbols, always ;)
