### ISSUE TITLE
Does not work with Angular 11

### ISSUE THREAD

**Issue by whoiscarlo** [gadicc/node-yahoo-finance2#153]
# Bug Report

## Describe the bug
Error: node_modules/yahoo-finance2/api/index-common.d.ts:1:8 - error TS1259: Module '"/Users/darknyte/Dropbox/Sandbox/angular/lucrative/node_modules/yahoo-finance2/api/lib/yahooFinanceFetch"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
    
    1 import yahooFinanceFetch from "./lib/yahooFinanceFetch";
             ~~~~~~~~~~~~~~~~~
    
      node_modules/yahoo-finance2/api/lib/yahooFinanceFetch.d.ts:1:1
        1 export = yahooFinanceFetch;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

## Minimal Reproduction
Create a brand new angular project

`ng new yahoo-test`
install yahoo-finance2:
`npm i yahoo-finance2`

In *app.component.ts*
add `import yahooFinance from 'yahoo-finance2';`
Save file 
Then run `ng serve`

[Repo Link](https://github.com/whoiscarlo/yahoo-finance-test)

## Environment
Node version :  v15.4.0
Npm version:  7.11.2
Angular: 11.0.5
Typescript: 4.0.2
TS Lint: 6.1.0
TS-Node: 8.3.0

**Comment by gadicc** [comment]
Hey @whoiscarlo, thanks for reporting.

I don't have any experience with Angular but this seems to be a TypeScript error, so not sure why we haven't noticed it before.  Looking at the typescript docs for [allowSyntheticDefaultImports](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports), it sounds like you can either set this option to `true` in your `tsconfig.json` or perhaps try:

```js
import * as yahooFinance from "yahoo-finance2"
```

I'll note also that we're busy working on better module support in #144, which will probably land later this week or next week, which should result in you being able to import yahoo-finance2 like normal and without any special flags.  (Also, importing as in the above might break when this lands, so changing the config option (temporarily) is probably a safer bet).

Please leave this issue open and we'll update when the above code is merged and released.

**Comment by gadicc** [comment]
Oh and, on another note, this package (and the original) aren't well suited for running in the browser.  We made sure in this release to make sure it can be loaded in the browser, but network requests to Yahoo's servers will be blocked by CORS, and you'll need a proxy server to get around that.  There's a small note about it in the README (on this repo).  However, if you're using this server-side with Angular you'll be fine (I don't really know exactly how the ng build process works).

**Comment by whoiscarlo** [comment]
@gadicc dude you're the man!! Thanks for even taking the time to respond to this. I'll try out that solution and see how it goes. 

I be honest and admit I didn't fully read the README as I should have 😓  and just dived, in so I'll be better with that next time. And as a completed noob developer I had no idea what a CORS error was or how to get around it, so after 2 days of messing around I built myself a small Go-Fiber rest api and started querying data from Yahoo's API directly 😅

**Comment by gadicc** [comment]
Great stuff, happy I could help.  Sure, see how you go.  And maybe it's not a bad idea for us to log a warning to the console when used in the browser, I've surely badly skimmed READMEs before in my time.

**Comment by gadicc** [comment]
Hey @whoiscarlo, I don't think you're actually still using `node-yahoo-finance2` anymore, but just in case, the new module support (which has been in `devel` for a while) was just released (and @PythonCreator27 added an extra warning in the browser console that refers back to the README).  I'm closing for now but in case you are still using this, please do report back :)
