### ISSUE TITLE
Add expiration date to the query for loading option chains

### ISSUE THREAD

**Issue by MiErnst** [gadicc/node-yahoo-finance2#175]
# Feature Request
When using the API I'm unable to pass in the expiration date of the option chain to query. By default it currently loads the option chain of the nearest expiration. 

## Wanted Feature
Add support for the query parameter "date" which accepts a timestamp like in this example: https://query1.finance.yahoo.com/v7/finance/options/X?date=1622160000

The available timestamps are available in the result of the default statement when using the API as is:
```
expirationDates: [
1621555200,
1622160000,
1622764800,
...
]
```

## Use Cases
-  Querying options chains for a specific expiration would allow me to implement my trade management for the expirations I have chosen. Only having access to the nearest option chain does not help.
- Without the argument, the API doesn't seem to make sense for me.

## Potential Example Usage
This feature *could* be used in the following way:
```ts
  const queryOptions = { lang: 'en-US', formatted: false, region: 'US', date: 1622160000};
  const result = await yahooFinance.options('TSLA', queryOptions);
```

**Comment by PythonCreator27** [comment]
My fault. I forgot to add this when I created the module. Will send PR soon.

**Comment by gadicc** [comment]
@MiErnst, this will be in the next release.  There'll be an automatic message here once it's available via npm.

That might only be in another week or two so you're invited to run the development version of the library until then if you like and feel comfortable with it, as described in [CONTRIBUTING.md](https://github.com/gadicc/node-yahoo-finance2/blob/devel/CONTRIBUTING.md).  Please report back if you do.

**Comment by MiErnst** [comment]
Thanks for the support.
