### ISSUE TITLE
Historical module removed by mistake?

### ISSUE THREAD

**Issue by okomarov** [gadicc/node-yahoo-finance2#200]
# Bug Report

## Describe the bug
It seems that: https://github.com/gadicc/node-yahoo-finance2/commit/4603232698e168c8893a275828b860fece748f1f#diff-1053484f5a0528ed4685340b3a56e56da363fb9e32229da71e2d8d30537d63fd

has remove the historical module by mistake?

**Comment by PythonCreator27** [comment]
Oops... my mistake. This is a very unintended regression. Created #201 to fix.

**Comment by gadicc** [comment]
@PythonCreator27, haha, looks like we both took this on at the same time...  but I beat you by about 1m ;)

@okomarov, thanks for reporting and for hunting this down!

Funny that we have over 1,000 tests and none of them check that we actually include all the modules :sweat_smile:   Guess we should add an integration test for it.

**Comment by okomarov** [comment]
Fixed in f75040206bf23ce4446f87066633423424348efc
