### ISSUE TITLE
Handle 'null' numbers when importing

### ISSUE THREAD

**Issue by okomarov** [gadicc/node-yahoo-finance2#208]
# Bug Report

## Describe the bug
Symbol [EURGBP=X](https://uk.finance.yahoo.com/quote/EURGBP%3DX/history?period1=1570492800&period2=1570579200&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true) has no records for '2019-10-09', so when queried historically is filled with nulls (check the .csv import from the link).

I'd expect the numbers to be `null` not the stringified `'null'`.

## Minimal Reproduction
```typescript
const queryOptions = { period1: '2019-10-08', period2: '2019-10-09' };
const res = await yahooFinance.historical(symbol, queryOptions, { validateResult: false });
console.log(res);
```
produces:
```typescript
[
  {
    date: 2019-10-08T00:00:00.000Z,
    open: 0.89283,
    high: 0.89988,
    low: 0.8922,
    close: 0.8928,
    adjClose: 0.8928,
    volume: 0
  },
  {
    date: 2019-10-09T00:00:00.000Z,
    open: 'null',
    high: 'null',
    low: 'null',
    close: 'null',
    adjClose: 'null',
    volume: 'null'
  }
]
```
The same output with 'null' is produced when the result is validated.

## Environment
Node version (if applicable): 14.17.0
yarn version: 1.22.10
Library version (e.g. 1.10.1): 1.12.1

**Comment by gadicc** [comment]
Hey @okomarov, thanks for reporting this and especially for the concise link.

Wow, this is a great find.  I've never seen this before, and I wonder if it's something specific to currencies.  As you probably saw, Yahoo usually just skips the days it has no data for (including for "EURGBP=X") .  It's quite weird to give us just a date with no data.

I'm actually wondering how best to handle this.
Maybe we should just silently skip such rows (and perhaps add an option to include them regardless).

I know that as a developer, I'd prefer to just know that I'm getting valid data back, and not need to check each result too.

Please let me know your thoughts.
I'd also like to consider this a bit more myself.

In particular, I wonder if there are any entries where *some but not all* fields are null.
Or if the only time this occurs is when *all* fields are null.

**Comment by okomarov** [comment]
Yes, it seems to be happening for conversions. I would simply skip as it's not news that Yahoo has some weird stuff happening with their API/data.  Another weird behaviour is getting no data if you actually historically query only `2019-10-09`.

So, if you want reliable data, you should probably pay for it and get a more reliable source. I am taking this tradeoff as I will internally fetch the most recent rate and don't mind some approximation.

**Comment by gadicc** [comment]
Thanks, @okomarov.

If you want you try the feature branch `history-null`, otherwise I don't see anything worrying there and will probably merge and publish in the coming days.

I didn't look / think much yet about the single date query on a null row.  But if we're skipping these kinds of rows now, and that query returns no rows anyway, then I guess there's nothing really to do here ^_^

**Comment by gadicc** [comment]
TODO: document the new behaviour.
