### ISSUE TITLE
Windows - Error: Cannot find module 'ajv-formats'

### ISSUE THREAD

**Issue by kuworking** [gadicc/node-yahoo-finance2#236]
# Bug Report

## Describe the bug
Installed and trying to use it for the first time, I get the error `Error: Cannot find module 'ajv-formats'`

## Minimal Reproduction

```
const yahooFinance = require('yahoo-finance2').default;
```

Only importing yahooFinance (electron-forge environment) causes the message

## Environment
Browser or Node: node
Node version (if applicable): 
Npm version: 12.17

## Additional Context

```
  "dependencies": {
    "@fontsource/roboto": "4.2.1",
    "@fontsource/staatliches": "4.2.1",
    "cors": "2.8.5",
    "electron-squirrel-startup": "^1.0.0",
    "express": "4.17.1",
    "fs-extra": "8.0.0",
    "isomorphic-unfetch": "3.1.0",
    "papaparse": "5.3.1",
    "path": "0.12.7",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "styled-components": "^5.3.0",
    "yahoo-finance2": "^1.14.0"
  },
  "devDependencies": {
    "@babel/core": "^7.14.6",
    "@babel/preset-react": "^7.14.5",
    "@electron-forge/cli": "^6.0.0-beta.57",
    "@electron-forge/maker-deb": "^6.0.0-beta.57",
    "@electron-forge/maker-rpm": "^6.0.0-beta.57",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.57",
    "@electron-forge/maker-zip": "^6.0.0-beta.57",
    "@electron-forge/plugin-webpack": "6.0.0-beta.57",
    "@marshallofsound/webpack-asset-relocator-loader": "^0.5.0",
    "babel-loader": "^8.2.2",
    "babel-plugin-styled-components": "^1.13.1",
    "copy-webpack-plugin": "^9.0.1",
    "css-loader": "^5.0.0",
    "electron": "13.1.5",
    "node-loader": "^2.0.0",
    "prettier": "2.3.2",
    "style-loader": "^2.0.0"
  }
```

**Comment by gadicc** [comment]
Hey @kuworking, thanks for reporting.

That's... strange :sweat_smile: 

What happens if you delete your `node_modules` directory and run `npm install` again?

Or if you `npm install ajv-formats` directly?  I mean, you really shouldn't need to do that, but I'm curious if it makes a difference.

I don't have any experience with Windows or electron-forge, but whatever your environment, installing the package should really just work.

I noticed you also have react, babel, etc...  do you have the same issue with `import yahooFinance from "yahoo-finance2"` (vs `require`'ing it?).

Failing all that, if you can provide a minimal reproduction with electron-forge, I'll happily take a look.

**Comment by PythonCreator27** [comment]
@kuworking Could you also post your NPM version? That may help with debugging the issue.

**Comment by kuworking** [comment]
*Fast reply
- NPM 6.14.4
- I'm using `yarn`
- Using `yahoo-finance` works as expected
- I'm using `require` because I'm using the "server" part from the electron app (node). I haven't tried using it from the frontend but it wouldn't work anyway (without proxies or something I'd say)

I'll write back asap, thanks :)

**Comment by gadicc** [comment]
hey @kuworking, thanks for squeezing in this reply.  Ok, understood.

When you have a chance, I'd suggest stopping the whole app, deleting the `node_modules` directory, and running `yarn install` again, and see if that makes a difference.

**Comment by kuworking** [comment]
Hello again,

I have created this minimal repo that fails on windows with the same message. Hope it can help!

https://github.com/kuworking/delete_finance

**Comment by kuworking** [comment]
Just tested with version 2.1.1 and the error is still there

![image](https://user-images.githubusercontent.com/4474004/151653491-020ec485-2726-483c-a5ea-9c0c6824bd39.png)

**Comment by gadicc** [comment]
Hey @kuworking, thanks for the update and for your patience.

I've looked into this and found a few examples of people having encountered similar issues on other projects.  Seems to be an issue with webpack/electron and npm/yarn module resolution of `ajv` in some circumstances (other packages or their dependencies using different versions of `ajv{,-*}`.  I didn't actually find anywhere where someone had figured out the exact cause, but it seems there's any easy workaround: `yarn add ajv` in your project.

I tested this on your repo with today's release of `yahoo-finance2` (v2.1.2) which uses the latest versions of `ajv` and `ajv-formats`, but on Linux.  Please confirm whether or not this works around the issue for you.

**Comment by 4vanger** [comment]
Just got similar issue. Workaround it to `npm i ajv ajv-formats -D` - it will force NPM install those packages into `node_modules` where they could be found
