### ISSUE TITLE
Failed validation: #/definitions/InsightsResult

### ISSUE THREAD

**Issue by hantechis** [gadicc/node-yahoo-finance2#253]
# Validation Error

## Symbol(s) that it happened for
- 
- 
- 

## Error Message

```

```

## Environment
Browser or Node: 
Node version (if applicable): 
Npm version: 
Browser verion (if applicable):
Library version (e.g. `1.10.1`): 

## Additional Context

The following result did not validate with schema: #/definitions/InsightsResult
[
  {
    instancePath: '',
    schemaPath: '#/additionalProperties',
    keyword: 'additionalProperties',
    params: { additionalProperty: 'upsell' },
    message: 'must NOT have additional properties'
  }
]

This may happen intermittently and you should catch errors appropriately.
However:  1) if this recently started happening on every request for a symbol
that used to work, Yahoo may have changed their API.  2) If this happens on
every request for a symbol you've never used before, but not for other
symbols, you've found an edge-case.  Please see if anyone has reported
this previously:

  https://github.com/gadicc/node-yahoo-finance2/issues?q=is%3Aissue+Failed%20validation%3A%20%23%2Fdefinitions%2FInsightsResult

or open a new issue (and mention the symbol):

  https://github.com/gadicc/node-yahoo-finance2/issues/new?labels=bug%2C+validation&template=validation.md&title=Failed%20validation%3A%20%23%2Fdefinitions%2FInsightsResult

For information on how to turn off the above logging or skip these errors,
see https://github.com/gadicc/node-yahoo-finance2/tree/devel/docs/validation.md.

{
  "name": "FailedYahooValidationError",
  "result": {
    "symbol": "ABBOTINDIA.NS",
    "upsell": {
      "companyName": "ABBOTT INDIA LTD",
      "upsellReportType": "MORNINGSTAR_ANALYST"
    },
    "sigDevs": [
      {
        "headline": "Abbott India Dec-Qtr Net Profit Slips",
        "date": "2021-02-09T00:00:00.000Z"
      }
    ]
  },
  "errors": [
    {
      "instancePath": "",
      "schemaPath": "#/additionalProperties",
      "keyword": "additionalProperties",
      "params": {
        "additionalProperty": "upsell"
      },
      "message": "must NOT have additional properties"
    }
  ]
}

**Comment by gadicc** [comment]
Hey @hantechis, thanks for reporting this!  First time we've come across this field.  It's fixed in the devel branch and should be released quite soon (there'll be an automatic message here when it is).  If this is common on the NSE stocks and you encounter any further problems, please do let us know!  Thanks :pray:
