### ISSUE TITLE
Docs: Add missing responses of submodules in quoteSummary documentation

### ISSUE THREAD

**Issue by RoXioTD** [gadicc/node-yahoo-finance2#260]
# Docs Improvment

## Suggested Improvement
Complete the example responses of the quoteSummary submodules.

## Reason For Suggestion
Currently some submodules of the quoteSummary module dont have any example responses. This makes it hard to work with these submodules, since you dont know the reponse structure of the submodule. See the following image, which represents the current state of the `devel` branch.
![image](https://user-images.githubusercontent.com/34741282/129440404-19dda299-bd6d-4f57-9e65-72232ae76a5c.png)

I already started documenting some submodules in a fork, which can be seen here: [quoteSummary.md](https://github.com/RoXioTD/node-yahoo-finance2/blob/devel/docs/modules/quoteSummary.md)

If you are agreeing with me on this Issue I would be pleased to document more submodules and create a PR.

TODO
- [x] cashflowStatementHistoryQuarterly
- [x] fundOwnership
- [x] fundPerformance
- [x] fundProfile
- [x] incomeStatementHistory
- [x] incomeStatementHistoryQuarterly
- [x] indexTrend
- [x] industryTrend
- [x] insiderHolders
- [x] insiderTransactions
- [x] institutionOwnership
- [x] majorDirectHolders
- [x] majorHoldersBreakdown
- [x] netSharePurchaseActivity
- [x] quoteType
- [x] recommendationTrend
- [x] sectorTrend

**Comment by gadicc** [comment]
Yes please, @RoXioTD!  That will be absolutely amazing and super appreciated :pray: :pray:

**Comment by RoXioTD** [comment]
- [ ] cashflowStatementHistoryQuarterly
- [ ] fundOwnership
- [ ] fundPerformance
- [ ] fundProfile
- [ ] incomeStatementHistory
- [ ] incomeStatementHistoryQuarterly
- [ ] indexTrend
- [ ] industryTrend
- [ ] insiderHolders
- [ ] insiderTransactions
- [ ] institutionOwnership
- [ ] majorDirectHolders
- [ ] majorHoldersBreakdown
- [ ] netSharePurchaseActivity
- [ ] quoteType
- [ ] recommendationTrend
- [ ] secFilings
- [ ] sectorTrend

**Comment by gadicc** [comment]
Uh, as a note... docs go live straight away... so this wasn't actually only "released" now as hinted by the auto message above :sweat_smile:
