### ISSUE TITLE
Failed to Compile

### ISSUE THREAD

**Issue by musiice** [gadicc/node-yahoo-finance2#306]
# Bug Report
I have been unable to get yahoo-finance2 to work, and thought it had to do with my setup. So I created a fresh project

1. npx create-react-app myapp
After this npm start works fine

2. npm i yahoo-finance2
After installting yahoo-finance2 and calling it, I get the error below.

> Failed to compile.
> 
> ./node_modules/yahoo-finance2/dist/esm/src/lib/validateAndCoerceTypes.js 161:57
> Module parse failed: Unexpected token (161:57)
> File was processed with these loaders:
>  * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
> | /* istanbul ignore next */
> |
> > const logObj = typeof process !== "undefined" && process?.stdout?.isTTY ? obj => console.dir(obj, {
> |   depth: 4,
> |   colors: true

**Test code**

const yahooFinance = require('yahoo-finance2').default;
(async function() {
  const result = await yahooFinance.quoteSummary('AAPL');
  const qPostMarket = result.price.postMarketPrice;
  console.log(qPostMarket);
})

I have no clue on what is the issue, and search doesn't return much help either.

**Comment by gadicc** [comment]
I'll just add that I'm using this in a CRA project, I'm not sure which versions this is an issue for, but I think we can sidestep it our side just like others have done.  More info in that other issue.
