### ISSUE TITLE
Intraday interval support

### ISSUE THREAD

**Issue by felixsanz** [gadicc/node-yahoo-finance2#334]
python's yfinance library admits `valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo`. But this `historical()` function only admits `"1d", "1wk", "1mo"`. It is possible to have intraday intervals?

**Comment by gadicc** [comment]
Hey, yahoo-finance2 `historical()` module uses Yahoo's `historical` API under the hood, which indeed only supports `"1d", "1wk", "1mo"` intervals.  (Ref: https://github.com/pilwon/node-yahoo-finance/pull/76)

I had a look at yfinance, and it looks like [their history module uses Yahoo's `chart` API](https://github.com/ranaroussi/yfinance/blob/9eef951acc70121e65825ad25e7afd2edd4c3e4b/yfinance/base.py#L180) (vs their "history" API), to get that data.  This is an approach we're exploring too, and we hope to have a dev release very soon.

You can follow the relevant issues, particularly #328.  You can leave this issue open and we'll update here too.
