### ISSUE TITLE
autoc no longer works

### ISSUE THREAD

**Issue by gadicc** [gadicc/node-yahoo-finance2#337]
```bash
$ yahoo-finance autoc GOOGL

Exiting with FetchError: invalid json response body at https://autoc.finance.yahoo.com/autoc?region=1&lang=en&query=GOOGL reason: Unexpected token < in JSON at position 0
```

Reason:

```bash
$ wget "https://autoc.finance.yahoo.com/autoc?region=1&lang=en&query=Goo"
--2021-11-21 15:33:12--  https://autoc.finance.yahoo.com/autoc?region=1&lang=en&query=Goo
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving autoc.finance.yahoo.com (autoc.finance.yahoo.com)... 87.248.100.208
Connecting to autoc.finance.yahoo.com (autoc.finance.yahoo.com)|87.248.100.208|:443... connected.
HTTP request sent, awaiting response... 404 Not Found on Accelerator
2021-11-21 15:33:12 ERROR 404: Not Found on Accelerator.
```

Looks like Yahoo have simply decommissioned their autoc server.  The autocomplete on yahoo finance uses `search` under the hood anyways, so we should advise accordingly.

**Comment by gadicc** [comment]
Also mentioned in https://github.com/gadicc/node-yahoo-finance2/blob/devel/docs/modules/quote.md#query-options.

**Comment by mozeryansky** [comment]
Is there a way to mark the function deprecated or maybe delete the autoc code? I just ran into this issue and I was about to file a bug, good to know it's already known and addressed here.

**Comment by gadicc** [comment]
Err, yes.  Not sure why I thought to update all the docs and leave all the code in.  I think maybe I didn't mean to close the issue from the commit and then forgot about it after I did.  Thanks for raising this!

**Comment by mozeryansky** [comment]
Awesome, thanks! It's a great package, I'm glad it's active.
