### ISSUE TITLE
Inaccurate Earnings Dates

### ISSUE THREAD

**Issue by glintik** [gadicc/node-yahoo-finance2#386]
# Bug Report

Unfortunately, Earnings Dates from YF are full of inacurate and misleading data.

### Example of approximate earnings dates(a.k.a. _unconfirmed_) from quote call for Intel(**$INTC**)
```
  earningsTimestamp: 2021-10-21T20:00:00.000Z,
  earningsTimestampStart: 2022-04-20T20:00:00.000Z,
  earningsTimestampEnd: 2022-04-25T20:00:00.000Z,
```
As I can see, YF just generates some date range based on previous date. You can see that earningsTimestampStart != earningsTimestampEnd.
The problem is that real earnings event was hold yesterday, Jan 26.

### Example of confirmed earnings date from quote call for PayPal(**$PYPL**)
```
  earningsTimestamp: 2022-02-02T00:00:00.000Z,
  earningsTimestampStart: 2022-02-02T00:00:00.000Z,
  earningsTimestampEnd: 2022-02-02T00:00:00.000Z,
```
As shown on [official website](https://investor.pypl.com/news-and-events/events/event-details/2022/PayPals-Q4-2021-Earnings-Call/default.aspx), PayPal’s Q4 2021 Earnings Call is expected on FEBRUARY 1, 2022 02:00 PM PT.
So even for "confirmed" date YF provides wrong date. As you can see, time is full of nulls and I found that if time contain some value, then date is correct when earningsTimestampStart == earningsTimestampEnd. Time in date is for information purposes only and usually wrong, but I found that for many cases if time is <= opening bell time, then earnings will be unveiled BEFORE market open.

I think, docs should warn about that Earnings Dates are full of inacurate and misleading data and better to use another source.

**Comment by gadicc** [comment]
Thanks @glintik, this is very helpful to know.  I agree and have added a note about this in the docs, with a link back to this issue.  Thanks for reporting!
