### ISSUE TITLE
Failed validation: #/definitions/QuoteResponse

### ISSUE THREAD

**Issue by pudgereyem** [gadicc/node-yahoo-finance2#42]
## Issue

The `QuoteResponse` for a norwegian stock [ArcticZymes Technologies ($AZT.OL)](https://finance.yahoo.com/quote/AZT.OL?p=AZT.OL&.tsrc=fin-srch) is missing a bunch of properties that are currently required. See the missing properties below:

```
"quoteSourceName",
"averageDailyVolume3Month",
"averageDailyVolume10Day",
"fiftyDayAverage",
"fiftyDayAverageChange",
"fiftyDayAverageChangePercent",
"twoHundredDayAverage",
"twoHundredDayAverageChange",
"twoHundredDayAverageChangePercent",
"firstTradeDateMilliseconds",
```

## How to replicate

Simply add `AZT.OL` to `quote.spec.ts` and you will see that the schema doesn't validate.

## Proposed solution

Change the missing properties to be optional.

**Comment by pudgereyem** [comment]
@gadicc I created a PR that fixes this, please see https://github.com/gadicc/node-yahoo-finance2/pull/43

**Comment by gadicc** [comment]
Thanks, as usual, @pudgereyem! :pray:
