### ISSUE TITLE
Link from every module doc to the type defs

### ISSUE THREAD

**Issue by gadicc** [gadicc/node-yahoo-finance2#425]
E.g.

"The example output above does not cover all possible return results, which can vary by asset type and even time of day (trading period).  For an exhausting list of everything we cover and that you might get back, please see the TypeScript interface in LINK."

**Comment by glaucoheitor** [comment]
I'm not into TS yet but are there TypeScript interfaces links available already? If so, I can update the docs with the proper links, if not, point me on how to create those and I can put everything together for the docs. :)

**Comment by gadicc** [comment]
Oh, yes!  That would be a huge help!  Thanks for this kind offer.

It's literally just a matter of placing a link from e.g. `docs/modules/quote.md` to `src/modules/quote.ts`.

The only exception is `quoteSummary.md`... because the results are so big, we put all the interfaces in a separate file, `quoteSummary-iface.ts`.

I would place the example paragraph I gave above directly under the sample output from in the docs from running the command.  Maybe with a "Note:" before :)  Or whatever makes sense to you as a user of the library :)

I think best to use the link directly (as "http://....") so it's very clear what's being linked to and how we keep track of these things.

Did that all make sense?
Don't hesitate to ask me about anything that's not clear...
This will be a great help for me and of course all users who will see this sooner now :pray:

**Comment by glaucoheitor** [comment]
I've added the links with the disclaimer. Also added a commit to 2 small typos, let me know if that can be improved further.

I wish I could help with the code itself, but I have hard time understanding TypeScript.

**Comment by gadicc** [comment]
Legend!  It was such a pleasure to receive this, thank you! :pray:   Been meaning to add something like this for so long, finally opened an issue to remind myself, and you just appeared and took it on.  Honestly, with the limited time I have to work on this, these kinds of PRs are so helpful to me.  So thanks again.

Don't worry, I'm sure you'll have an opportunity to help with the code in the future too :)  And I totally get what you're saying about the TypeScript.  But if it makes you feel better, you should know that this is actually my first and only TypeScript project to date.  It's just a really good fit especially in terms of all the validation.

As a first step, I guess you saw what the "interfaces" look like.  It's basically just an API contract that says, e.g., "if we give you back a Quote, it will have the following fields, and those fields will be of these types (string, number, date, etc).".  Besides being helpful to developers, that's then converted into a json schema (in `schema.json`) which is processed by regular JS schema validation tools as you might use on any form input.

But for developers, it really adds a lot to developers... besides making sure that you can't write code that can break with unexpected results, you also get really nice autocompletion, as you maybe saw in the animated gif in the main README.  Anyways, if you're ever interested (maybe some toilet reading), I believe I started off with this [typescript in 5 minutes](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html) guide.

**Comment by gadicc** [comment]
Oh, don't worry about the release message above... obviously docs are always shown as the most up-to-date version on github, and aren't packaged inside npm.
