### ISSUE TITLE
Failed validation for FUTURE quotes (e.g. "GC=F")

### ISSUE THREAD

**Issue by dtslvr** [gadicc/node-yahoo-finance2#449]
# Validation Error

## Minimal Reproduction
```
await yahooFinance.quote("GC=F");
```

## Symbol(s) that it happened for
- `GC=F` (gold)
- `SI=F` (silver)
- `HG=F` (copper)

## Error Message
```
The following result did not validate with schema: #/definitions/QuoteResponseArray
[
  {
    instancePath: '/0',
    schemaPath: '#/anyOf',
    keyword: 'anyOf',
    params: {},
    message: 'must match a schema in anyOf',
    data: '[shortened by validateAndCoerceTypes]'
  }
]
```

## Environment
Browser or Node: `browser` (CodeSandbox) and `node`
Library version: `2.3.1`

**Comment by gadicc** [comment]
Thanks @dtslvr for reporting.  Seems you're the first to use the library with quotes of futures :sweat_smile: 

Fixed this in `quote` and `quoteSummary` and made sure that all other modules validate such symbols too (except `recommendationsBySymbol` which doesn't keep data for futures).

Thanks for reporting!  All fixed :)

**Comment by dtslvr** [comment]
> Thanks @dtslvr for reporting. Seems you're the first to use the library with quotes of futures 😅

Awesome! 😃 
I'm happy to try it here: https://github.com/ghostfolio/ghostfolio/pull/845

**Comment by gadicc** [comment]
Ah, great! :clap::tada:

**Comment by gadicc** [comment]
It's commit https://github.com/gadicc/node-yahoo-finance2/commit/56b664bd46098f432a46716c6b6b83d29f9537f2 btw if you want to see the new fields...  (skip the schema.json diff, see the changes to quote and quoteSummary, and then don't worry about all the cached tests).

**Comment by dtslvr** [comment]
Hey @gadicc

I have successfully upgraded `yahoo-finance2` to version `2.3.2` in [Ghostfolio 1.144.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.144.0) and it works like a charm. Thank you very much! 😎

**Comment by gadicc** [comment]
Great news!  Thanks for reporting back! :raised_hands::pray:
