### ISSUE TITLE
Error: "Got {}->null for 'number', did you want 'number | null' ?"

### ISSUE THREAD

**Issue by aturkkan94** [gadicc/node-yahoo-finance2#517]
# Bug Report

Hi, Im getting the error in the picture for specific symbols "EREGL.IS" "THYAO.IS". Maybe there are more symbols having the same error but i found only these...

![error](https://user-images.githubusercontent.com/66059183/184435920-7e2e6307-0f70-4eb3-81f0-ec672f4cbce0.jpg)

I'm thinking whether i did a mistake in my code or not but api was working perfectly before.

If you can fix the issue it would be great.

Thanks...

**Comment by gadicc** [comment]
Thanks for reporting, @aturkkan94.  Fixed in the latest release.

**Comment by aturkkan94** [comment]
Thanks for your quick response @gadicc .
EREGL.IS is working fine now.
But THYAO.IS is getting errors...
![thyao](https://user-images.githubusercontent.com/66059183/184471681-24b8bbda-2631-4940-bf72-a11375a9cf3c.jpg)

**Comment by gadicc** [comment]
Oh wow, that's my bad... I didn't check carefully enough and incorrectly assumed both were having the same error.  I'm on it, watch this space :)
