### ISSUE TITLE
Better way to log failed validation on large responses

### ISSUE THREAD

**Issue by gadicc** [gadicc/node-yahoo-finance2#55]
Quoting @pudgereyem in https://github.com/gadicc/node-yahoo-finance2/pull/47#issuecomment-779490840:

> 2) Developer experience when a test fails with a very large response
I tried to trigger the errors that you got yourself for the added symbols on a branch of my own. Since the response from the quoteSummary module is so large I had to scroll up thousands and thousands of lines to see the actual error. What I did was to comment out this line to just see the validation errors.

My ideal would be to only show the errors but WITH the data that causes that error, which ajv doesn't do currently.  Will look into further.

(i.e. it will say `marketState bust be "OPEN" | "CLOSED"` etc, but not what the actual value was that failed the test).

**Comment by pudgereyem** [comment]
@gadicc Good idea! We could also maybe create a link that opens up the cached response in your editor, e.g tests/http/example.json?

**Comment by gadicc** [comment]
Well, no one has complained yet :sweat_smile:  and I've found this useful in my own tests, so, closing for now.  Will re-open if anyone adds anything here.
