### ISSUE TITLE
Prettier with editorconfig

### ISSUE THREAD

**Issue by gadicc** [gadicc/node-yahoo-finance2#56]
@pudgereyem, thanks again for #37.  I wanted to check up on this...   for every file now we get this:

```bash
$ yarn prettier -c .
yarn run v1.22.10
$ /home/dragon/www/npm/node-yahoo-finance2/node_modules/.bin/prettier -c .

Checking formatting...
[warn] Ignored unknown option { editorconfig: true }.
[warn] Ignored unknown option { editorconfig: true }.
[warn] Ignored unknown option { editorconfig: true }.
[warn] Ignored unknown option { editorconfig: true }.
```

I did some looking up a while back (but then got distracted so don't have the links anymore), and `editorconfig: true` is not a `prettierrc` option, it's an option when using the prettier API from another package.

I'm happy to leave this in if it fixes issues for people using Visual Studio, but I wonder if there might be a more correct way to get the VS plugin to work like this.  From the prettier side, they say it will always use an `.editorconfig` file if found.

**Comment by pudgereyem** [comment]
Hey @gadicc!

> I did some looking up a while back (but then got distracted so don't have the links anymore), and editorconfig: true is not a prettierrc option, it's an option when using the prettier API from another package.

I see, interesting.

> I'm happy to leave this in if it fixes issues for people using Visual Studio, but I wonder if there might be a more correct way to get the VS plugin to work like this. From the prettier side, they say it will always use an .editorconfig file if found.

After doing some research I found a solution to the problem; by changing the Prettier configuration from `.prettierrc.yaml` to `.prettierrc.js`.

I think the reason behind this is is that our `.prettierrc.yaml` was completely empty, and therefore Visual Studio Code didn't pick it up as a configuration. Maybe has something to do with [Syntax for empty dictionary in YAML](https://stackoverflow.com/questions/33510094/syntax-for-empty-dictionary-in-yaml) - not saying that it is, but yeah.

I'm opening up a PR that'll fix this.

**Comment by pudgereyem** [comment]
@gadicc here we go; https://github.com/gadicc/node-yahoo-finance2/pull/59

**Comment by gadicc** [comment]
Hey @pudgereyem that's some great research there!

Don't hate me, but I'd prefer to keep the yaml file if possible... I find they're a lot clearer and more maintainable.  However, I see you edited your message and took out the SO link, so I'm guessing putting just `{}` in the yaml file still didn't work, in which case, happy to merge :)  (Unfortunately I don't have Visual Studio to test on)

**Comment by pudgereyem** [comment]
@gadicc, no worries at all! I thought it was weird to have `{}` in a `.yaml` file, but it works. Will update the PR :)

**Comment by pudgereyem** [comment]
@gadicc https://github.com/gadicc/node-yahoo-finance2/pull/59 💯

**Comment by gadicc** [comment]
Legend!!  Thanks, @pudgereyem :raised_hands:
