### ISSUE TITLE
Failed validation: #/definitions/OptionsResult

### ISSUE THREAD

**Issue by Lexus2016** [gadicc/node-yahoo-finance2#561]
# Validation Error

## Symbol(s) that it happened for
PYPL

## Error Message

The following result did not validate with schema: #/definitions/OptionsResult
[
  {
    instancePath: '/options/0/calls/57',
    schemaPath: '#/definitions/CallOrPut/required',
    keyword: 'required',
    params: { missingProperty: 'currency' },
    message: "must have required property 'currency'",
    data: {
      contractSymbol: 'PYPL221118C00103000',
      strike: 103,
      lastPrice: 0.05,
      change: -0.040000003,
      percentChange: -44.444447,
      volume: 57,
      openInterest: 37,
      bid: 0.02,
      ask: 0.04,
      contractSize: 'REGULAR',
      expiration: 2022-11-18T00:00:00.000Z,
      lastTradeDate: 2022-11-15T19:43:41.000Z,
      impliedVolatility: 0.6875031250000001,
      inTheMoney: false
    }
  },
  {
    instancePath: '/options/0/calls/58',
    schemaPath: '#/definitions/CallOrPut/required',
    keyword: 'required',
    params: { missingProperty: 'currency' },
    message: "must have required property 'currency'",
    data: {
      contractSymbol: 'PYPL221118C00104000',
      strike: 104,
      lastPrice: 0.05,
      change: -0.02,
      percentChange: -28.571426,
      volume: 35,
      openInterest: 12,
      bid: 0.02,
      ask: 0.04,
      contractSize: 'REGULAR',
      expiration: 2022-11-18T00:00:00.000Z,
      lastTradeDate: 2022-11-15T17:11:37.000Z,
      impliedVolatility: 0.726565234375,
      inTheMoney: false
    }
  },
  {
    instancePath: '/options/0/calls/60',
    schemaPath: '#/definitions/CallOrPut/required',
    keyword: 'required',
    params: { missingProperty: 'currency' },
    message: "must have required property 'currency'",
    data: {
      contractSymbol: 'PYPL221118C00106000',
      strike: 106,
      lastPrice: 0.03,
      change: -0.020000001,
      percentChange: -40.000004,
      volume: 87,
      openInterest: 86,
      bid: 0.01,
      ask: 0.03,
      contractSize: 'REGULAR',
      expiration: 2022-11-18T00:00:00.000Z,
      lastTradeDate: 2022-11-15T18:36:39.000Z,
      impliedVolatility: 0.7656273437500001,
      inTheMoney: false
    }
  },
  {
    instancePath: '/options/0/puts/58',
    schemaPath: '#/definitions/CallOrPut/required',
    keyword: 'required',
    params: { missingProperty: 'percentChange' },
    message: "must have required property 'percentChange'",
    data: {
      contractSymbol: 'PYPL221118P00102000',
      strike: 102,
      currency: 'USD',
      lastPrice: 11.4,
      change: 11.4,
      volume: 1,
      openInterest: 0,
      bid: 11.9,
      ask: 12.55,
      contractSize: 'REGULAR',
      expiration: 2022-11-18T00:00:00.000Z,
      lastTradeDate: 2022-11-15T18:54:22.000Z,
      impliedVolatility: 0.7597680273437502,
      inTheMoney: true
    }
  },
  {
    instancePath: '/options/0/puts/59',
    schemaPath: '#/definitions/CallOrPut/required',
    keyword: 'required',
    params: { missingProperty: 'currency' },
    message: "must have required property 'currency'",
    data: {
      contractSymbol: 'PYPL221118P00103000',
      strike: 103,
      lastPrice: 12.25,
      change: 12.25,
      volume: 1,
      openInterest: 0,
      bid: 12.85,
      ask: 13.65,
      contractSize: 'REGULAR',
      expiration: 2022-11-18T00:00:00.000Z,
      lastTradeDate: 2022-11-15T18:57:31.000Z,
      impliedVolatility: 0.8437515624999999,
      inTheMoney: true
    }
  },
  {
    instancePath: '/options/0/puts/59',
    schemaPath: '#/definitions/CallOrPut/required',
    keyword: 'required',
    params: { missingProperty: 'percentChange' },
    message: "must have required property 'percentChange'",
    data: {
      contractSymbol: 'PYPL221118P00103000',
      strike: 103,
      lastPrice: 12.25,
      change: 12.25,
      volume: 1,
      openInterest: 0,
      bid: 12.85,
      ask: 13.65,
      contractSize: 'REGULAR',
      expiration: 2022-11-18T00:00:00.000Z,
      lastTradeDate: 2022-11-15T18:57:31.000Z,
      impliedVolatility: 0.8437515624999999,
      inTheMoney: true
    }
  },
  {
    instancePath: '/options/0/puts/61',
    schemaPath: '#/definitions/CallOrPut/required',
    keyword: 'required',
    params: { missingProperty: 'currency' },
    message: "must have required property 'currency'",
    data: {
      contractSymbol: 'PYPL221118P00106000',
      strike: 106,
      lastPrice: 14.9,
      change: 14.9,
      volume: 5,
      openInterest: 0,
      bid: 15.9,
      ask: 16.55,
      contractSize: 'REGULAR',
      expiration: 2022-11-18T00:00:00.000Z,
      lastTradeDate: 2022-11-15T19:21:28.000Z,
      impliedVolatility: 0.945313046875,
      inTheMoney: true
    }
  },
  {
    instancePath: '/options/0/puts/61',
    schemaPath: '#/definitions/CallOrPut/required',
    keyword: 'required',
    params: { missingProperty: 'percentChange' },
    message: "must have required property 'percentChange'",
    data: {
      contractSymbol: 'PYPL221118P00106000',
      strike: 106,
      lastPrice: 14.9,
      change: 14.9,
      volume: 5,
      openInterest: 0,
      bid: 15.9,
      ask: 16.55,
      contractSize: 'REGULAR',
      expiration: 2022-11-18T00:00:00.000Z,
      lastTradeDate: 2022-11-15T19:21:28.000Z,
      impliedVolatility: 0.945313046875,
      inTheMoney: true
    }
  }
]

(node:31663) UnhandledPromiseRejectionWarning: FailedYahooValidationError: Failed Yahoo Schema validation
    at validate (/Users/admin/Documents/_Projects/SeasonPatterns/back/node_modules/yahoo-finance2/dist/cjs/src/lib/validateAndCoerceTypes.js:298:15)
    at Object.<anonymous> (/Users/admin/Documents/_Projects/SeasonPatterns/back/node_modules/yahoo-finance2/dist/cjs/src/lib/moduleExec.js:96:53)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/admin/Documents/_Projects/SeasonPatterns/back/node_modules/yahoo-finance2/dist/cjs/src/lib/moduleExec.js:21:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31663) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Environment
Browser or Node: 
Node version (if applicable): v14.17.1
Npm version:  8.19.2
Browser verion (if applicable):
Library version (e.g. `1.10.1`):  2.3.9

**Comment by gadicc** [comment]
Thanks for another report.  Wish yahoo-fiance was more consistent, but that's why we have all this validation in place.  You know the drill :grin:... there'll be a message about a new release in a few minutes, please confirm when you have a chance :pray:

**Comment by Lexus2016** [comment]
It's okay!

**Comment by gadicc** [comment]
Great!  Thanks for reporting back :pray:
