### ISSUE TITLE
Chart Data with Futures Has Validation Error

### ISSUE THREAD

**Issue by jwd2a** [gadicc/node-yahoo-finance2#593]
Using the new `_chart` module with futures symbols results in a validation error seen below:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/1709781/212775533-560359c8-2a45-4cda-bf71-a8f5b2c5495d.png">

To reproduce:
```
const queryOptions = { period1: '2023-01-13', interval: '30m' };
const result = await yahooFinance2._chart("GC=F", queryOptions);
```

## Environment
Browser or Node: Node
Node version (if applicable): `14.19.2`
Npm version: `6.14.17`
Library version (e.g. `1.10.1`): `2.3.10`

**Comment by jwd2a** [comment]
Worth noting that there was a previous issue with futures validation here: https://github.com/gadicc/node-yahoo-finance2/issues/449

This appears to indicate this was solved in the chart module, but perhaps something changed?

**Comment by gadicc** [comment]
Legend!  Thanks.

I'm spread so thin lately these kind of admin comments are so greatly appreciated to!  :pray:
