### ISSUE TITLE
Failed validation: #/definitions/QuoteResponse | Symbol: BEKE, BFLY

### ISSUE THREAD

**Issue by short-term** [gadicc/node-yahoo-finance2#61]
## Issue
I tried to get queto of some ticker(BEKE, BFLY), but it returned these issues.

```javascript
// What I called
await yf.quote("BEKE");
await yf.quote("BFLY");
```
```javascript
// Response of BEKE
{
    keyword: 'additionalProperties',
    dataPath: '/0',
    schemaPath: '#/definitions/QuoteEquity/additionalProperties',
    params: { additionalProperty: 'ipoExpectedDate' },
    message: 'should NOT have additional properties',
    data: { .. }
}
// Response of BFLY
{
    keyword: 'additionalProperties',
    dataPath: '/0',
    schemaPath: '#/definitions/QuoteEquity/additionalProperties',
    params: { additionalProperty: 'newListingDate' },
    message: 'should NOT have additional properties',
    data: { .. }
}
```
## Comments
I simply added those property with optional to [quote.ts](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/quote.ts#L96).
```javascript
  trailingThreeMonthReturns?: number; // 16.98
  trailingThreeMonthNavReturns?: number; // 17.08
  ipoExpectedDate?: Date; // "2020-08-13",     <---- added
  newListingDate?: Date; // "2021-02-16",      <---- added
```
Also I add each queto-*.json files for test too.

<img width="322" alt="test" src="https://user-images.githubusercontent.com/57710054/108205954-16071600-7169-11eb-861c-b4e3455d2ec5.png">

**Comment by gadicc** [comment]
Hey @short-term, amazing to see a new issue that includes its own fix!  This is great; thanks for getting up to speed with everything so quickly :raised_hands:
