### ISSUE TITLE
Unable to fetch prices 

### ISSUE THREAD

**Issue by TechTronixx** [gadicc/node-yahoo-finance2#641]
# Bug Report

## Describe the bug
Unable to fetch stock prices 

## Environment
Browser or Node: 
Node version (if applicable): 
Npm version: 
Browser version (if applicable):
Library version (e.g. `1.10.1`): 

## Additional Context
Unable to fetch any Stock prices

**Comment by gadicc** [comment]
Hey @TechTronixx, thanks for the report and your patience.  I'm guessing this was related to all cookie and crumb issues back then, which were all fixed (ref https://github.com/gadicc/node-yahoo-finance2/issues/633).  If you're still experiencing any issues, please re-open, and provide the exact query which fails.  Thanks!
