### ISSUE TITLE
Search by ticker invalid?

### ISSUE THREAD

**Issue by Benjythebee** [gadicc/node-yahoo-finance2#657]
# Bug Report
If I search "META"; I get no response when I should be getting "Meta platforms"
If I search "ME"; I get multiple responses including "META"

Did I miss something?

## Minimal Reproduction
`let searchResult = await yahooFinance.search("META", {lang:'en-US',quotesCount:10,newsCount:0})`

## Environment
Node 18.17
yahoo-finance2: 2.4.2

**Comment by Benjythebee** [comment]
Interestingly, If I write `FB` I get META 😅

**Comment by gadicc** [comment]
Hey @Benjythebee, thanks for the report and for your patience.  I'm unable to reproduce this now.  Yahoo's services can be... finicky... at times.  It looks like they've fixed this on this end now.  Please feel free to re-open if you experience it again.
