### ISSUE TITLE
Error - Invalid Cookie

### ISSUE THREAD

**Issue by JabulaniSifundza** [gadicc/node-yahoo-finance2#660]
# Bug Report

## Describe the bug

I just updated to node-yahoo-finance-2 and have read the documentation on the update/migration, however I am still receiving the following error:
Error.name = "Error"
Error.message = "Invalid cookie"

## Minimal Reproduction

const {ticker} = req.body;
  try{
	const queryOptions = { modules: ['price', 'summaryDetail'] };
	const data = await yahooFinance.quoteSummary(ticker, queryOptions);
	res.status(200).json(data)
  }
  catch(error){
  	res.status(500).json({"error": error.name, "message": error.message)
  }

## Environment
Browser or Node: Node.js (Chrome browser)

## Additional Context
Thank you for your time and help!

**Comment by gadicc** [comment]
Hey @JabulaniSifundza, thanks for the report.  Could you please confirm what version you're using (I assume its the latest if you've just switched), the symbol, and the full output from the request?  There should be some lines like "Fetching crumb and cookies....".  Also, the symbol, and, what country you're in (Yahoo behaves differently in different countries due to differing data regulations).  Thanks!

**Comment by JabulaniSifundza** [comment]
Yeah of course!
The version is = yahoo-finance2: "^2.3.10"
The symbol I was testing was: AAPL
The error object/message: {error: "Error", message: "Invalid Cookie"}. This is from the catch block in the code.
I am currently in eSwatini. Were there recent additions to restrictions? Because it worked before with the previous version.

Thank you so much for your time and response!

**Comment by gadicc** [comment]
Ah ok, you're behind :)  Current release is 2.4.4.

The changes were all on Yahoo's side (tracking sessions, consent, etc).  We had to adapt the library to workaround that.

Upgrade to the latest version and you should be fine.  (But please report back and let us know).

**Comment by JabulaniSifundza** [comment]
Thank you so much! The update works perfectly. Thank you for all your help and also for creating this library!
