### ISSUE TITLE
Failed validation: #/definitions/InsightsResult

### ISSUE THREAD

**Issue by z3nful** [gadicc/node-yahoo-finance2#663]
# Bug Report

Using v2.4.6, I get the following validation errors from Insights:

-------------
Ticker: HIDV
The following result did not validate with schema: #/definitions/InsightsResult
[
  {
    instancePath: '/instrumentInfo/keyTechnicals',
    schemaPath: '#/properties/keyTechnicals/required',
    keyword: 'required',
    params: { missingProperty: 'stopLoss' },
    message: "must have required property 'stopLoss'",
    data: { provider: 'Trading Central' }
  }
]

-------------
Ticker: MPAY
The following result did not validate with schema: #/definitions/InsightsResult
[
  {
    instancePath: '/companySnapshot',
    schemaPath: '#/definitions/InsightsCompanySnapshot/required',
    keyword: 'required',
    params: { missingProperty: 'sectorInfo' },
    message: "must have required property 'sectorInfo'",
    data: {
      company: { insiderSentiments: 0.6469, earningsReports: 0.6367 },
      sector: {
        innovativeness: 0.5,
        hiring: 0.5,
        sustainability: 0.5,
        insiderSentiments: 0.5,
        earningsReports: 0.5,
        dividends: 0.5
      }
    }
  }
]

-------------
Ticker: RUSHA
The following result did not validate with schema: #/definitions/InsightsResult
[
  {
    instancePath: '/reports/1/targetPriceStatus',
    schemaPath: '#/definitions/InsightsReport/properties/targetPriceStatus/enum',
    keyword: 'enum',
    params: { allowedValues: [ 'Increased', 'Maintained', 'Decreased' ] },
    message: 'must be equal to one of the allowed values',
    data: '-'
  },
  {
    instancePath: '/upsellSearchDD/researchReports',
    schemaPath: '#/definitions/InsightsResearchReport/required',
    keyword: 'required',
    params: { missingProperty: 'investmentRating' },
    message: "must have required property 'investmentRating'",
    data: {
      reportId: 'MS_0P000004QQ_AnalystReport_1603736082000',
      provider: 'Morningstar',
      title: 'Dropping Coverage of Rush Enterprises',
      reportDate: 2020-10-26T18:14:42.000Z,
      summary: 'Rush Enterprises is the only publicly traded, standalone commercial truck dealer in North America. With 120 locations, it sells 5.6% of new class 8 trucks as the largest truck dealer on the continent. Vehicle sales include class 4-8 new trucks as well as range of used commercial vehicles. Aftermarket parts and service are key drivers of profitability as they generate approximately 30% of revenue and 65% of gross profit. Rush’s class 8 customers include large fleets (32%), mid-size fleets (16%), vocational customers (40%), and owner-operators (12%). In 2019, Rush generated $5.8 billion in revenue.'
    }
  }
]

**Comment by gadicc** [comment]
Reported and fixed with contributions from @z3nful; thanks! :pray:
