### ISSUE TITLE
Failed validation: #/definitions/QuoteSummaryResult

### ISSUE THREAD

**Issue by z3nful** [gadicc/node-yahoo-finance2#664]
# Validation Error

## Minimal Reproduction

const results = await yahooFinance.quoteSummary("EURN", {
     modules: ["secFilings"]
});

## Symbol(s) that it happened for
- EURN
- ARMK
- Other Foreign Companies

## Error Message

```
Same property for all of them
{
    instancePath: '/secFilings/filings/0/type',
    schemaPath: '#/definitions/Filing/properties/type/enum',
    keyword: 'enum',
    params: {
      allowedValues: [
        '10-K',     '10-Q',
        '8-K',      '8-K/A',
        '10-K/A',   '10-Q/A',
        'SD',       'PX14A6G',
        'SC 13G/A', 'DEFA14A',
        '25-NSE',   'S-8 POS'
      ]
    },
    message: 'must be equal to one of the allowed values',
    data: '6-K'
  }

```

## Environment
Browser or Node: 
Node version (if applicable): 
Npm version: 
Browser verion (if applicable):
Library version (e.g. `1.10.1`): 
2.4.6
## Additional Context

The following forms are all failing Validation:
6-K
F-3ASR
SC 13D/A
20-F
425 
SC14D9C
SC 13G
S-8
DEF 14A
F-10

**Comment by gadicc** [comment]
Reported and fixed by @z3nful; thanks! :pray:
