### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by aslak01** [gadicc/node-yahoo-finance2#685]
# Feature Request

## Wanted Feature
Hey, I was trying to set up a small Deno script to use this library with the recent `import xxx from 'npm:xxx'` addition. However it errors out on the request saying `[Error] Errors { invalid_mapping, disallowed_character }` (using the error handling from the docs). So I ported the script to Node just to check, and it works fine. 

I'm looking at historical data at the moment so I tried the `.chart` and `.historical` modules, none of the others. Turns out it's not a great fit for me anyway since some of the historical stocks are missing from yahoo, but I thought I'd mention it.

## Use Cases
- Deno is really great for having small standalone scripts working with files locally
- It's also great for running with github actions which could be a nice combination with this library

I think being able to interface with deno would be a good addition to a project like this.

**Comment by gadicc** [comment]
And thanks also for opening the issue even though you might not be using it moving forward :sweat_smile: :pray:

**Comment by z3nful** [comment]
It looks like its a bug with deno. Using the workaround from the following issue allowed me run it, but requires modifying one of the modules that deno uses: 

https://github.com/denoland/deno/issues/19238 

(Also, be careful if you copy paste the code from there, it has some odd blankspace formatting around the .'s)

**Comment by aslak01** [comment]
Wow that's odd, especially since from that issue it appears to me that the issue was solved and patched. At least it's not a problem for this repo then.

**Comment by z3nful** [comment]
I think its a zombie bug deno is dealing with lol 

I saw a few different posts during my research from the last few years saying it was gone, but that it would come back after a few versions, almost all of them based around that TLD it currently fails on

**Comment by aslak01** [comment]
Maybe you could make a new issue for them? Seems like you have a better understanding of the potential problem than I do.
