### ISSUE TITLE
It looks like quoteSummary now needs crumb

### ISSUE THREAD

**Issue by Yhprum** [gadicc/node-yahoo-finance2#686]
# Bug Report

## Describe the bug
https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL now requires a crumb (+cookie), and the module give the `Quote not found for ticker symbol` error.

## Minimal Reproduction
`await yahooFinance.quoteSummary("AAPL")`

## Environment
Browser or Node: Node
Node version: v18.15.0
Npm version: 9.5.0
Library version: ^2.7.0

**Comment by z3nful** [comment]
Its working for me under the same conditions, are you using a proxy that could be blocking the cookie call?

**Comment by Yhprum** [comment]
False alarm, it looks like it was a different error - I was searching for 
https://query1.finance.yahoo.com/v10/finance/quoteSummary/AAPL230929C00050000?crumb=RtmhBL3vfo5&modules=price,summaryDetail

which has the put option at that strike/expiry but not the call, so the error was from it just not being there. Sorry bout that and thanks for the confirmation!

**Comment by gadicc** [comment]
Thanks, @z3nful, and @Yhprum for reporting back!
