### ISSUE TITLE
ERROR in ./node_modules/yahoo-finance2/dist/esm/src/lib/fetchDevel.js 6:17-62

### ISSUE THREAD

**Issue by chiahao-codes** [gadicc/node-yahoo-finance2#703]
# Bug Report

## Describe the bug

I am getting the following error when running my code:

ERROR in ./node_modules/yahoo-finance2/dist/esm/src/lib/fetchDevel.js 6:17-62
Module not found: Error: Can't resolve '../../tests/http/' in 'C:\Desktop\Ticqer\node_modules\yahoo-finance2\dist\esm\src\lib'

I checked line 6 of the fetchDevel.js inside my node_modules folder. 
`const BASE_URL = new URL("../../tests/http/", import.meta.url);`
The /tests/http folder for creating a new URL does not seem to exist anywhere inside the parent folder.
Has anyone encountered this? Any help would be much appreciated.
## Environment
Browser or Node: 
Browser
Node version (if applicable): 
20.6.1
Npm version: 
8.1.2
Browser verion (if applicable):
Library version (e.g. `1.10.1`): 

## Additional Context
I am using Webpack 5.88.2 as my bundler.

**Comment by orelhochenboym** [comment]
Maybe related to this? #645

**Comment by nordicgit70** [comment]
Resolved with release v2.9.0.
