### ISSUE TITLE
Invalid Cookie or Invalid Crumb for options

### ISSUE THREAD

**Issue by mhozic** [gadicc/node-yahoo-finance2#736]
# Bug Report

## Describe the bug
When yahooFinance.options is called, "Invalid Cookie" or "Invalid Crumb" error is returned

## Minimal Reproduction
const response = yahooFinance.options('AYX')
throws "Invalid Cookie" or "Invalid Crumb" error

## Environment
Browser or Node: node
Node version (if applicable): 14.18.2
Npm version: 6.14.15
Library version: 2.9.0

## Additional Context
/v6/finance/options/ endpoint doesn't produce this error
/v7/finance/options/ needs a crumb (needsCrumb: true)

**Comment by samducker** [comment]
cc: @gadicc

**Comment by gadicc** [comment]
Sam, thanks for the report, the ping and your patience.  I just got back
from a long overseas trip and am catching up on everything.  I hope to get
to this on Sunday or Monday 🙏

**Comment by samducker** [comment]
No worries thank you for this library and your amazing work @gadicc I felt bad to tag :D, but I have a client on my back. 

In the meantime I introduced a caching solution on my end which has limited the impact of my problem. So no worries, enjoy the weekend.

Happy to follow up with my sentry logs if helpful. 

p.s. 

I am happy to submit a PR, if you can point me in the right direction also <3!
