### ISSUE TITLE
Receiving this error message: "error": "Could not find window.YAHOO.context. Yahoo's API may have changed; please report."

### ISSUE THREAD

**Issue by martincsl** [gadicc/node-yahoo-finance2#746]
# Bug Report

## Describe the bug
I was normally using the API until today, when an error started to show: "error": "Could not find window.YAHOO.context. Yahoo's API may have changed; please report."

## Minimal Reproduction
const result = await yahooFinance.quote("GOOG");

## Environment
Browser or Node: Node
Node version (if applicable): v16.13.0
Npm version: 
Browser verion (if applicable):
Library version (e.g. `1.10.1`):

**Comment by gadicc** [comment]
Hey @martincsl, thanks for the report.  Can you confirm if this is still happening?  I checked now and am not experiencing any issues.  Yahoo's servers do occasionally have short lived issues, that can temporarily cause these kinds of issues, but get resolved on Yahoo's side.  I guess I should add a note about that too.

**Comment by martincsl** [comment]
Hi Gady, now it's working! Thanks a lot for your response! It would be nice to add a note for future reference.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by gadicc** [comment]
Hey @martincsl, (belated) thanks for reporting back, and agree re a more helpful note.  The text now reads:

> Could not find window.YAHOO.context.  This is usually caused by temporary issues on Yahoo's servers that tend to resolve themselves; however, if the error persists for more than 12 hours, Yahoo's API may have changed, and you can help by reporting the issue.  Thanks :)

and this will be in the next release.  Thanks again.
