### ISSUE TITLE
Error: Could not find window.YAHOO.context. Yahoo's API may have changed; please report.

### ISSUE THREAD

**Issue by sonminhnguyen** [gadicc/node-yahoo-finance2#775]
# Bug Report

## Describe the bug

Hi everyone. I got this error message when try to access fundamental reports of a stock. Anyone know how to fix it?
P/S: Searching for a stock worked normally
## Minimal Reproduction

![bug](https://github.com/gadicc/node-yahoo-finance2/assets/33770081/d20af759-306b-4437-a034-c1aa60432c07)

## Environment
Browser or Node: 
Node version (if applicable): v16.19.1
Npm version: 8.19.3
Browser verion (if applicable): Microsoft Edge Version 124.0.2478.97
Library version (e.g. `1.10.1`): 2.11.2

**Comment by gadicc** [comment]
Hey @sonminhnguyen, something is very weird here, because in your report it says you're using v2.11.2 (latest), but the error shown doesn't exist in that release, only in releases <= 2.11.0.  What does

```bash
$ grep version node_modules/yahoo-finance2/package.json
```

in you project root dir say?

**Comment by sonminhnguyen** [comment]
Hi. I ran your command. And it returned this

![image](https://github.com/gadicc/node-yahoo-finance2/assets/33770081/71e4bb3b-e381-4404-8fc0-5866d3a2c127)

This is my code and result when I called the API. 

![image](https://github.com/gadicc/node-yahoo-finance2/assets/33770081/474fb849-c4f8-4696-917c-001e82da7147)
![image](https://github.com/gadicc/node-yahoo-finance2/assets/33770081/bab17e79-1b05-4654-b427-3e0674f84ed5)

**Comment by gadicc** [comment]
Hey, thanks for the follow up.  Sorry, I'm traveling, so my responses will be erratic.  Sorry about that. 

It's pretty weird because again, that error doesn't exist in the latest version (we released a fix to fix exactly that, and removed that code path).

What framework are you using?  What package manager?  Is there a way you could clear your cache and try again?  e.g. `rm -r .next/cache` for nextjs.

**Comment by sonminhnguyen** [comment]
I fixed it by deleting node_modules and installing everything again. I just want to say thank you to you and your team for this miraculous package. I used it for over 4 years, and it still helps me a lot :)
