### ISSUE TITLE
Warning message expecting a redirect to guce.yahoo.com

### ISSUE THREAD

**Issue by Emre4x0** [gadicc/node-yahoo-finance2#778]
# Validation Error

## Minimal Reproduction
`await yahooFinance.quote('AAPL')`

## Error Message
```
We expected a redirect to guce.yahoo.com, but got https://finance.yahoo.com/quote/AAPL/
We'll try to continue anyway - you can safely ignore this if the request succeeds
```

## Environment
Browser or Node: Node
Library version (e.g. `1.10.1`): 2.11.3

## Additional Context

Hello, when I use “quote” in version 2.11.3, the above message appears in my console.

How can I turn off this message?

**Comment by arochaa** [comment]
The same issue here.
[Nest] 53911  - 05/31/2024, 11:07:57 AM   ERROR [ExceptionsHandler] Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.
Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.

**Comment by Langsdorf** [comment]
updating to 2.11.3 solved the problem

check https://github.com/gadicc/node-yahoo-finance2/releases/tag/v2.11.3

**Comment by Emre4x0** [comment]
> updating to 2.11.3 solved the problem
> 
> check https://github.com/gadicc/node-yahoo-finance2/releases/tag/v2.11.3

i am currently using version 2.11.3. the problem persists.

**Comment by Langsdorf** [comment]
@Emre4x0 sorry, i was referring to @arochaa problem,

seems that you can't disable those messages:

![image](https://github.com/gadicc/node-yahoo-finance2/assets/13462281/02825c16-e94e-4553-a9e7-96756e2b3565)

**Comment by gadicc** [comment]
You can override the logger as per the docs:

https://github.com/gadicc/node-yahoo-finance2/blob/devel/docs/other/setGlobalConfig.md#logger

what's logged by default will be improved in the future, we've just had bigger fish to fry until now (i.e. keeping the library working every time Yahoo changes something 😅).

**Comment by Emre4x0** [comment]
> You can override the logger as per the docs:
> 
> 
> 
> https://github.com/gadicc/node-yahoo-finance2/blob/devel/docs/other/setGlobalConfig.md#logger
> 
> 
> 
> what's logged by default will be improved in the future, we've just had bigger fish to fry until now (i.e. keeping the library working every time Yahoo changes something 😅).

i got it, thank you for your work. the module saves my life. thank you for your response. have a nice weekend. 😇

**Comment by gadicc** [comment]
thanks for the kind words.  you too  😁 🙏
