### ISSUE TITLE
Typo in function name message vs export: supressNotices vs. suppressNotices

### ISSUE THREAD

**Issue by sid-the-sloth** [gadicc/node-yahoo-finance2#845]
# bad message about function supressNotices

## Describe the bug
Trying to suppress notices, according to the output to console:

```
Please consider completing the survey at https://bit.ly/yahoo-finance-api-feedback if you haven't already; for more info see https://github.com/gadicc/node-yahoo-finance2/issues/764#issuecomment-2056623851.  This will only be shown once, but you can suppress this message in future with `yahooFinance.supressNotices(['yahooSurvey'])`.
```

Please note the spelling in above message: `yahooFinance.supressNotices(['yahooSurvey'])`.

If you try to use that, nodejs will show an error, of course:

`TypeError: yahooFinance.supressNotices is not a function`

Looking through the source file `node-yahoo-finance2/src/lib/notices.ts` in this repo, the code shows a different name for the function name (proper English spelling: "suppress"):

`export function suppressNotices(noticeIds: (keyof typeof notices)[]) {...}`

Please fix the spelling of the message to match the exported function name.

**Comment by gadicc** [comment]
Thanks so much, @sid-the-sloth!  This will be in the next release.  Thanks for the detailed report 🙏
